# Generated by Django 2.1.7 on 2019-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblConsultancyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('procurement_title', models.TextField(blank=True, null=True)),
                ('procurement_name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('publish_date', models.TextField(blank=True, null=True)),
                ('close_date', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('tender_notice', models.TextField(blank=True, null=True)),
                ('bidding_document', models.TextField(blank=True, null=True)),
                ('page_no', models.IntegerField()),
                ('row_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
